name: "CI (Integração Continua): Primeira Action"

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # Ativa esse fluxo de trabalho para cada push ou pull que acontecer para branch main
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# Definindo o que queremos executar
jobs:
  # primeira action
  example: #job: exemplo
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
